write blocks retrieved from the exchange to the blockstore
ipfs/go-blockservice pull request #92
Opened 2022-07-08 17:17 UTC by MichaelMure

This follows the change in bitswap where that responsibility was removed (https://github.com/ipfs/go-bitswap/pull/571).

2022-07-08 17:17 UTC, MichaelMure commented
cc @Jorropo

2022-07-27 09:06 UTC, MichaelMure commented on blockservice.go
> +			// TODO: for performance reason, it might make sense to batch those writes
> That's not perfect, but it'll help as long as rblocks is buffered (IIRC, it is).

Turns out, it's not buffered: https://github.com/ipfs/go-bitswap/blob/b18a91d6023b83821c72253bbe5e37190db64d63/internal/getter/getter.go#L93

2022-07-27 10:18 UTC, MichaelMure commented
I added the Put batching, tests to make sure that blockservice does write blocks, and followed the interface changes.

Again, we need to release and bubble up the dependency. I think the last remaining point is possibly to buffer the output channel in bitswap: https://github.com/ipfs/go-blockservice/pull/92#discussion_r930813860

2022-07-27 16:18 UTC, Jorropo requested changes
LGTM

2022-07-27 16:18 UTC, Jorropo commented on blockservice.go
> +		err = bs.Put(ctx, blk)
For posterity.
We discussed with @MichaelMure and since bitswap's client `GetBlock` call should be "pure", it's our responsability to callback into bitswap server `NotifyNewBlocks`.

2022-07-27 20:07 UTC, Jorropo commented
Blocking in https://github.com/MichaelMure/go-blockservice/pull/1

2022-07-28 03:15 UTC, Jorropo commented
The batch loop was too confusing, I rewrote it (hopefully) slightly better.

I would like a merge review on 30ca6aad09fdc64f3cda352c3a2a52468df7ceb1 pls.

2022-07-28 03:16 UTC, Jorropo approved these changes
LGTM, let's dog food this

2022-07-28 03:16 UTC, merged

2022-07-28 08:58 UTC, MichaelMure commented
> I would like a merge review on https://github.com/ipfs/go-blockservice/commit/30ca6aad09fdc64f3cda352c3a2a52468df7ceb1 pls.

LGTM